/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BindDiscord: typeof import('./src/components/user/bind-discord.vue')['default']
    BindOsu: typeof import('./src/components/user/bind-osu.vue')['default']
    BindQq: typeof import('./src/components/user/bind-qq.vue')['default']
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    List: typeof import('./src/components/message-box/list.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MessageBox: typeof import('./src/components/message-box/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1: typeof import('./src/components/register/step-1.vue')['default']
    Step2: typeof import('./src/components/register/step-2.vue')['default']
    Step3: typeof import('./src/components/register/step-3.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default']
    TabItem: typeof import('./src/components/tab-bar/tab-item.vue')['default']
  }
}
