/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BindDiscord: typeof import('./src/components/user/bind-discord.vue')['default']
    BindOsu: typeof import('./src/components/user/bind-osu.vue')['default']
    BindQq: typeof import('./src/components/user/bind-qq.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NResult: typeof import('naive-ui')['NResult']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1: typeof import('./src/components/register/step-1.vue')['default']
    Step2: typeof import('./src/components/register/step-2.vue')['default']
    Step3: typeof import('./src/components/register/step-3.vue')['default']
  }
}
